/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'experiential' : IDL.Null,
  'omnichannel' : IDL.Null,
  'inStoreTech' : IDL.Null,
  'aiDriven' : IDL.Null,
  'supplyChain' : IDL.Null,
  'sustainability' : IDL.Null,
  'ecommerce' : IDL.Null,
});
export const CostTier = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const RetailIdea = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'trending' : IDL.Bool,
  'shortDescription' : IDL.Text,
  'category' : Category,
  'estimatedCostTier' : CostTier,
  'fullDescription' : IDL.Text,
  'implementationDifficulty' : Difficulty,
  'opportunityScore' : IDL.Nat,
});
export const ImpactLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const MarketTrend = IDL.Record({
  'id' : IDL.Nat,
  'impactLevel' : ImpactLevel,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'affectedCategories' : IDL.Vec(Category),
});

export const idlService = IDL.Service({
  'addIdea' : IDL.Func([RetailIdea], [IDL.Nat], []),
  'addMarketTrend' : IDL.Func([MarketTrend], [IDL.Nat], []),
  'filterIdeas' : IDL.Func(
      [IDL.Opt(Category), IDL.Opt(CostTier), IDL.Opt(IDL.Vec(IDL.Nat))],
      [IDL.Vec(RetailIdea)],
      ['query'],
    ),
  'filterIdeasByBudget' : IDL.Func(
      [CostTier],
      [IDL.Vec(RetailIdea)],
      ['query'],
    ),
  'filterIdeasByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(RetailIdea)],
      ['query'],
    ),
  'getAllIdeas' : IDL.Func([], [IDL.Vec(RetailIdea)], ['query']),
  'getAllMarketTrends' : IDL.Func([], [IDL.Vec(MarketTrend)], ['query']),
  'getIdea' : IDL.Func([IDL.Nat], [RetailIdea], ['query']),
  'getIdeasByCategory' : IDL.Func([Category], [IDL.Vec(RetailIdea)], ['query']),
  'getSavedIdeas' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getTrendingIdeas' : IDL.Func([], [IDL.Vec(RetailIdea)], ['query']),
  'populateInitialData' : IDL.Func([], [], []),
  'saveIdea' : IDL.Func([IDL.Nat], [], []),
  'unsaveIdea' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'experiential' : IDL.Null,
    'omnichannel' : IDL.Null,
    'inStoreTech' : IDL.Null,
    'aiDriven' : IDL.Null,
    'supplyChain' : IDL.Null,
    'sustainability' : IDL.Null,
    'ecommerce' : IDL.Null,
  });
  const CostTier = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const RetailIdea = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'trending' : IDL.Bool,
    'shortDescription' : IDL.Text,
    'category' : Category,
    'estimatedCostTier' : CostTier,
    'fullDescription' : IDL.Text,
    'implementationDifficulty' : Difficulty,
    'opportunityScore' : IDL.Nat,
  });
  const ImpactLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const MarketTrend = IDL.Record({
    'id' : IDL.Nat,
    'impactLevel' : ImpactLevel,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'affectedCategories' : IDL.Vec(Category),
  });
  
  return IDL.Service({
    'addIdea' : IDL.Func([RetailIdea], [IDL.Nat], []),
    'addMarketTrend' : IDL.Func([MarketTrend], [IDL.Nat], []),
    'filterIdeas' : IDL.Func(
        [IDL.Opt(Category), IDL.Opt(CostTier), IDL.Opt(IDL.Vec(IDL.Nat))],
        [IDL.Vec(RetailIdea)],
        ['query'],
      ),
    'filterIdeasByBudget' : IDL.Func(
        [CostTier],
        [IDL.Vec(RetailIdea)],
        ['query'],
      ),
    'filterIdeasByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(RetailIdea)],
        ['query'],
      ),
    'getAllIdeas' : IDL.Func([], [IDL.Vec(RetailIdea)], ['query']),
    'getAllMarketTrends' : IDL.Func([], [IDL.Vec(MarketTrend)], ['query']),
    'getIdea' : IDL.Func([IDL.Nat], [RetailIdea], ['query']),
    'getIdeasByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(RetailIdea)],
        ['query'],
      ),
    'getSavedIdeas' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getTrendingIdeas' : IDL.Func([], [IDL.Vec(RetailIdea)], ['query']),
    'populateInitialData' : IDL.Func([], [], []),
    'saveIdea' : IDL.Func([IDL.Nat], [], []),
    'unsaveIdea' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };