/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'experiential' : null } |
  { 'omnichannel' : null } |
  { 'inStoreTech' : null } |
  { 'aiDriven' : null } |
  { 'supplyChain' : null } |
  { 'sustainability' : null } |
  { 'ecommerce' : null };
export type CostTier = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export type ImpactLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface MarketTrend {
  'id' : bigint,
  'impactLevel' : ImpactLevel,
  'name' : string,
  'description' : string,
  'affectedCategories' : Array<Category>,
}
export interface RetailIdea {
  'id' : bigint,
  'title' : string,
  'tags' : Array<string>,
  'trending' : boolean,
  'shortDescription' : string,
  'category' : Category,
  'estimatedCostTier' : CostTier,
  'fullDescription' : string,
  'implementationDifficulty' : Difficulty,
  'opportunityScore' : bigint,
}
export interface _SERVICE {
  'addIdea' : ActorMethod<[RetailIdea], bigint>,
  'addMarketTrend' : ActorMethod<[MarketTrend], bigint>,
  'filterIdeas' : ActorMethod<
    [[] | [Category], [] | [CostTier], [] | [Array<bigint>]],
    Array<RetailIdea>
  >,
  'filterIdeasByBudget' : ActorMethod<[CostTier], Array<RetailIdea>>,
  'filterIdeasByCategory' : ActorMethod<[Category], Array<RetailIdea>>,
  'getAllIdeas' : ActorMethod<[], Array<RetailIdea>>,
  'getAllMarketTrends' : ActorMethod<[], Array<MarketTrend>>,
  'getIdea' : ActorMethod<[bigint], RetailIdea>,
  'getIdeasByCategory' : ActorMethod<[Category], Array<RetailIdea>>,
  'getSavedIdeas' : ActorMethod<[], Array<bigint>>,
  'getTrendingIdeas' : ActorMethod<[], Array<RetailIdea>>,
  'populateInitialData' : ActorMethod<[], undefined>,
  'saveIdea' : ActorMethod<[bigint], undefined>,
  'unsaveIdea' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];