/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RetailIdea {
    id: bigint;
    title: string;
    tags: Array<string>;
    trending: boolean;
    shortDescription: string;
    category: Category;
    estimatedCostTier: CostTier;
    fullDescription: string;
    implementationDifficulty: Difficulty;
    opportunityScore: bigint;
}
export interface MarketTrend {
    id: bigint;
    impactLevel: ImpactLevel;
    name: string;
    description: string;
    affectedCategories: Array<Category>;
}
export enum Category {
    experiential = "experiential",
    omnichannel = "omnichannel",
    inStoreTech = "inStoreTech",
    aiDriven = "aiDriven",
    supplyChain = "supplyChain",
    sustainability = "sustainability",
    ecommerce = "ecommerce"
}
export enum Difficulty {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum ImpactLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export interface backendInterface {
    addIdea(idea: RetailIdea): Promise<bigint>;
    addMarketTrend(trend: MarketTrend): Promise<bigint>;
    filterIdeas(category: Category | null, budget: CostTier | null, trendIds: Array<bigint> | null): Promise<Array<RetailIdea>>;
    filterIdeasByBudget(costTier: CostTier): Promise<Array<RetailIdea>>;
    filterIdeasByCategory(category: Category): Promise<Array<RetailIdea>>;
    getAllIdeas(): Promise<Array<RetailIdea>>;
    getAllMarketTrends(): Promise<Array<MarketTrend>>;
    getIdea(id: bigint): Promise<RetailIdea>;
    getIdeasByCategory(category: Category): Promise<Array<RetailIdea>>;
    getSavedIdeas(): Promise<Array<bigint>>;
    getTrendingIdeas(): Promise<Array<RetailIdea>>;
    populateInitialData(): Promise<void>;
    saveIdea(ideaId: bigint): Promise<void>;
    unsaveIdea(ideaId: bigint): Promise<void>;
}
import type { Category as _Category, CostTier as _CostTier, Difficulty as _Difficulty, ImpactLevel as _ImpactLevel, MarketTrend as _MarketTrend, RetailIdea as _RetailIdea } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addIdea(arg0: RetailIdea): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addIdea(to_candid_RetailIdea_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIdea(to_candid_RetailIdea_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMarketTrend(arg0: MarketTrend): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMarketTrend(to_candid_MarketTrend_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMarketTrend(to_candid_MarketTrend_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async filterIdeas(arg0: Category | null, arg1: CostTier | null, arg2: Array<bigint> | null): Promise<Array<RetailIdea>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterIdeas(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterIdeas(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterIdeasByBudget(arg0: CostTier): Promise<Array<RetailIdea>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterIdeasByBudget(to_candid_CostTier_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterIdeasByBudget(to_candid_CostTier_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterIdeasByCategory(arg0: Category): Promise<Array<RetailIdea>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterIdeasByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterIdeasByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllIdeas(): Promise<Array<RetailIdea>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIdeas();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIdeas();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMarketTrends(): Promise<Array<MarketTrend>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMarketTrends();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMarketTrends();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIdea(arg0: bigint): Promise<RetailIdea> {
        if (this.processError) {
            try {
                const result = await this.actor.getIdea(arg0);
                return from_candid_RetailIdea_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIdea(arg0);
            return from_candid_RetailIdea_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIdeasByCategory(arg0: Category): Promise<Array<RetailIdea>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIdeasByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIdeasByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSavedIdeas(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedIdeas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedIdeas();
            return result;
        }
    }
    async getTrendingIdeas(): Promise<Array<RetailIdea>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingIdeas();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingIdeas();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async populateInitialData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.populateInitialData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.populateInitialData();
            return result;
        }
    }
    async saveIdea(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveIdea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveIdea(arg0);
            return result;
        }
    }
    async unsaveIdea(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsaveIdea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsaveIdea(arg0);
            return result;
        }
    }
}
function from_candid_Category_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_CostTier_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CostTier): CostTier {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ImpactLevel_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImpactLevel): ImpactLevel {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_MarketTrend_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketTrend): MarketTrend {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_RetailIdea_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RetailIdea): RetailIdea {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    tags: Array<string>;
    trending: boolean;
    shortDescription: string;
    category: _Category;
    estimatedCostTier: _CostTier;
    fullDescription: string;
    implementationDifficulty: _Difficulty;
    opportunityScore: bigint;
}): {
    id: bigint;
    title: string;
    tags: Array<string>;
    trending: boolean;
    shortDescription: string;
    category: Category;
    estimatedCostTier: CostTier;
    fullDescription: string;
    implementationDifficulty: Difficulty;
    opportunityScore: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        tags: value.tags,
        trending: value.trending,
        shortDescription: value.shortDescription,
        category: from_candid_Category_n19(_uploadFile, _downloadFile, value.category),
        estimatedCostTier: from_candid_CostTier_n21(_uploadFile, _downloadFile, value.estimatedCostTier),
        fullDescription: value.fullDescription,
        implementationDifficulty: from_candid_Difficulty_n23(_uploadFile, _downloadFile, value.implementationDifficulty),
        opportunityScore: value.opportunityScore
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    impactLevel: _ImpactLevel;
    name: string;
    description: string;
    affectedCategories: Array<_Category>;
}): {
    id: bigint;
    impactLevel: ImpactLevel;
    name: string;
    description: string;
    affectedCategories: Array<Category>;
} {
    return {
        id: value.id,
        impactLevel: from_candid_ImpactLevel_n28(_uploadFile, _downloadFile, value.impactLevel),
        name: value.name,
        description: value.description,
        affectedCategories: from_candid_vec_n29(_uploadFile, _downloadFile, value.affectedCategories)
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experiential: null;
} | {
    omnichannel: null;
} | {
    inStoreTech: null;
} | {
    aiDriven: null;
} | {
    supplyChain: null;
} | {
    sustainability: null;
} | {
    ecommerce: null;
}): Category {
    return "experiential" in value ? Category.experiential : "omnichannel" in value ? Category.omnichannel : "inStoreTech" in value ? Category.inStoreTech : "aiDriven" in value ? Category.aiDriven : "supplyChain" in value ? Category.supplyChain : "sustainability" in value ? Category.sustainability : "ecommerce" in value ? Category.ecommerce : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): ImpactLevel {
    return "low" in value ? ImpactLevel.low : "high" in value ? ImpactLevel.high : "medium" in value ? ImpactLevel.medium : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): Difficulty {
    return "easy" in value ? Difficulty.easy : "hard" in value ? Difficulty.hard : "medium" in value ? Difficulty.medium : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RetailIdea>): Array<RetailIdea> {
    return value.map((x)=>from_candid_RetailIdea_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MarketTrend>): Array<MarketTrend> {
    return value.map((x)=>from_candid_MarketTrend_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Array<Category> {
    return value.map((x)=>from_candid_Category_n19(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CostTier_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CostTier): _CostTier {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Difficulty_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_ImpactLevel_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImpactLevel): _ImpactLevel {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_MarketTrend_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketTrend): _MarketTrend {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_RetailIdea_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RetailIdea): _RetailIdea {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category | null): [] | [_Category] {
    return value === null ? candid_none() : candid_some(to_candid_Category_n3(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CostTier | null): [] | [_CostTier] {
    return value === null ? candid_none() : candid_some(to_candid_CostTier_n5(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<bigint> | null): [] | [Array<bigint>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    impactLevel: ImpactLevel;
    name: string;
    description: string;
    affectedCategories: Array<Category>;
}): {
    id: bigint;
    impactLevel: _ImpactLevel;
    name: string;
    description: string;
    affectedCategories: Array<_Category>;
} {
    return {
        id: value.id,
        impactLevel: to_candid_ImpactLevel_n11(_uploadFile, _downloadFile, value.impactLevel),
        name: value.name,
        description: value.description,
        affectedCategories: to_candid_vec_n12(_uploadFile, _downloadFile, value.affectedCategories)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    tags: Array<string>;
    trending: boolean;
    shortDescription: string;
    category: Category;
    estimatedCostTier: CostTier;
    fullDescription: string;
    implementationDifficulty: Difficulty;
    opportunityScore: bigint;
}): {
    id: bigint;
    title: string;
    tags: Array<string>;
    trending: boolean;
    shortDescription: string;
    category: _Category;
    estimatedCostTier: _CostTier;
    fullDescription: string;
    implementationDifficulty: _Difficulty;
    opportunityScore: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        tags: value.tags,
        trending: value.trending,
        shortDescription: value.shortDescription,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        estimatedCostTier: to_candid_CostTier_n5(_uploadFile, _downloadFile, value.estimatedCostTier),
        fullDescription: value.fullDescription,
        implementationDifficulty: to_candid_Difficulty_n7(_uploadFile, _downloadFile, value.implementationDifficulty),
        opportunityScore: value.opportunityScore
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    experiential: null;
} | {
    omnichannel: null;
} | {
    inStoreTech: null;
} | {
    aiDriven: null;
} | {
    supplyChain: null;
} | {
    sustainability: null;
} | {
    ecommerce: null;
} {
    return value == Category.experiential ? {
        experiential: null
    } : value == Category.omnichannel ? {
        omnichannel: null
    } : value == Category.inStoreTech ? {
        inStoreTech: null
    } : value == Category.aiDriven ? {
        aiDriven: null
    } : value == Category.supplyChain ? {
        supplyChain: null
    } : value == Category.sustainability ? {
        sustainability: null
    } : value == Category.ecommerce ? {
        ecommerce: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImpactLevel): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == ImpactLevel.low ? {
        low: null
    } : value == ImpactLevel.high ? {
        high: null
    } : value == ImpactLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == Difficulty.easy ? {
        easy: null
    } : value == Difficulty.hard ? {
        hard: null
    } : value == Difficulty.medium ? {
        medium: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Category>): Array<_Category> {
    return value.map((x)=>to_candid_Category_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
